fx_version("cerulean")
game("gta5")

client_script("lib/common.lua")
client_script("lib/observers/interiorIdObserver.lua")
client_script("lib/observers/officeSafeDoorHandler.lua")
client_script("client.lua")

client_script("gtav/base.lua")
client_script("gtav/ammunations.lua")
client_script("gtav/bahama.lua")
client_script("gtav/floyd.lua")
client_script("gtav/franklin.lua")
client_script("gtav/franklin_aunt.lua")
client_script("gtav/graffitis.lua")
client_script("gtav/lester_factory.lua")
client_script("gtav/michael.lua")
client_script("gtav/north_yankton.lua")
client_script("gtav/red_carpet.lua")
client_script("gtav/simeon.lua")
client_script("gtav/stripclub.lua")
client_script("gtav/trevors_trailer.lua")
client_script("gtav/ufo.lua")
client_script("gtav/zancudo_gates.lua")

client_script("gta_online/apartment_hi_1.lua")
client_script("gta_online/apartment_hi_2.lua")
client_script("gta_online/house_hi_1.lua")
client_script("gta_online/house_hi_2.lua")
client_script("gta_online/house_hi_3.lua")
client_script("gta_online/house_hi_4.lua")
client_script("gta_online/house_hi_5.lua")
client_script("gta_online/house_hi_6.lua")
client_script("gta_online/house_hi_7.lua")
client_script("gta_online/house_hi_8.lua")
client_script("gta_online/house_mid_1.lua")
client_script("gta_online/house_low_1.lua")

client_script("dlc_high_life/apartment1.lua")
client_script("dlc_high_life/apartment2.lua")
client_script("dlc_high_life/apartment3.lua")
client_script("dlc_high_life/apartment4.lua")
client_script("dlc_high_life/apartment5.lua")
client_script("dlc_high_life/apartment6.lua")

client_script("dlc_heists/carrier.lua")
client_script("dlc_heists/yacht.lua")

client_script("dlc_executive/apartment1.lua")
client_script("dlc_executive/apartment2.lua")
client_script("dlc_executive/apartment3.lua")

client_script("dlc_finance/office1.lua")
client_script("dlc_finance/office2.lua")
client_script("dlc_finance/office3.lua")
client_script("dlc_finance/office4.lua")
client_script("dlc_finance/organization.lua")

client_script("dlc_bikers/cocaine.lua")
client_script("dlc_bikers/counterfeit_cash.lua")
client_script("dlc_bikers/document_forgery.lua")
client_script("dlc_bikers/meth.lua")
client_script("dlc_bikers/weed.lua")
client_script("dlc_bikers/clubhouse1.lua")
client_script("dlc_bikers/clubhouse2.lua")
client_script("dlc_bikers/gang.lua")

client_script("dlc_import/garage1.lua")
client_script("dlc_import/garage2.lua")
client_script("dlc_import/garage3.lua")
client_script("dlc_import/garage4.lua")
client_script("dlc_import/vehicle_warehouse.lua")

client_script("dlc_gunrunning/bunkers.lua")
client_script("dlc_gunrunning/yacht.lua")

client_script("dlc_smuggler/hangar.lua")

client_script("dlc_doomsday/facility.lua")

client_script("dlc_afterhours/nightclubs.lua")
