local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- title (optional): group display name
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)

cfg.groups = {
	["ledelse"] = {
		"blacklisted.weapons",
		"blacklisted.vehicles",
		"player.group.add.staff",
		"player.group.remove.staff",
		"player.givemoney",
		"player.whitelist",
		"anticheese.bypass",
		"player.unwhitelist",
		"player.noclip",
		"player.giveitem",
		"player.ban",
		"vehicle.repair",
		"player.kick",
		"player.unban",
		"staff.seizable",
		"fire.start",
		"police.seize.items",
		"police.seize.weapons",
		"player.coords",
		"player.coordsnoheading",
		"admin.besked",
		"admin.revive",
		"player.unlockvehicle",
		"player.repairvehicle",
		"player.deletevehicle",
		"staff.gun",
		"player.spawnvehicle",
		"admin.easy_unjail",
		"admin.spikes",
		"player.tptowaypoint",
		"player.tptome",
		"player.tpto",
		"player.tptocoords",
		"player.freeze",
		"staff.chat",
		"admin.tickets",
		"player.list",
		"admin.godmode",
		"admin.revive",
		"ledelse.fix",
		"staff.revive",
		"Mekaniker.dv",
		"staff.chattitle",
	},
	["Hitman"] = {
		"hitman.door",
		"hitman.clothing",
		"hitman.weapon",
	},

	["Admin"] = {
		"player.deletevehicle",
		"player.ban",
		"player.unban",
		"player.group.add.staff",
		"player.group.remove.staff",
		"admin.besked",
		"player.coords",
		"admin.tickets",
		"anticheese.bypass",
		"staff.gun",
		"player.unlockvehicle",
		"admin.announce",
		"player.kick",
		"police.menu",
		"staff.seizable",
		"player.repairvehicle",
		"police.seize.weapons",
		"police.seize.items",
		"police.easy_cuff",
		"admin.revive",
		"player.tptowaypoint",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.tpto",
		"player.freeze",
		"staff.chat",
		"player.noclip",
		"admin.revive",
		"ledelse.fix",
		"staff.revive",
		"Mekaniker.dv",
		"staff.chattitle",
	},
	["Staff"] = {
		"player.deletevehicle",
		"player.ban",
		"admin.besked",
		"player.coords",
		"admin.tickets",
		"player.ban",
		"staff.gun",
		"anticheese.bypass",
		"player.unlockvehicle",
		"admin.announce",
		"player.kick",
		"police.menu",
		"staff.seizable",
		"player.repairvehicle",
		"police.seize.weapons",
		"police.seize.items",
		"police.easy_cuff",
		"admin.revive",
		"player.tptowaypoint",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.tpto",
		"player.freeze",
		"staff.chat",
		"player.noclip",
		"admin.revive",
		"ledelse.fix",
		"staff.revive",
		"Mekaniker.dv",
		"staff.chattitle",
	},
	["Supporter"] = {
		"admin.tickets",
		"player.deletevehicle",
		"admin.besked",
		"admin.revive",
		"player.coords",
		"admin.announce",
		"player.kick",
		"player.tptowaypoint",
		"anticheese.bypass",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.unlockvehicle",
		"player.tpto",
		"player.freeze",
		"staff.chat",
		"player.noclip",
		"staff.chattitle",
	},
	["P-Supporter"] = {
		"admin.tickets",
		"player.deletevehicle",
		"admin.besked",
		"admin.revive",
		"player.coords",
		"player.tptowaypoint",
		"anticheese.bypass",
		"player.list",
		"player.tptome",
		"player.tptocoords",
		"player.tpto",
		"staff.chat",
		"player.noclip",
		"staff.chattitle",
	},
	["Ban"] = {
		"player.ban",
	},
	["Gruppe"] = {
		"player.group.add.staff",
		"player.group.remove.staff",
	},
	["user"] = {
		"player.phone",
		"player.calladmin",
		"player.coords",
		"police.askid",
		"police.store_weapons",
		"user.askid",
		"police.seizable",
		"player.player_menu",
		"player.check",
		"player.store_armor",
		"player.store_weapons",
		"player.fix_haircut",
		"player.loot",
		"player.store_money",
		"player.strip",
		"player.drag",
		"player.putoutveh",
		"player.putinveh",
	},
	["EMS-Job"] = {
		"emergency.revive",
		"player.deletevehicle",
		"emergency.shop",
		"emergency.service",
		"emergency.market",
		"emergency.putinveh",
		"retsag.key",
		"emergency.besked",
		"emergency.getoutveh",
		"pd.key",
		"emergency.drag",
		"emergency.heal",
		"emergency.garage",
		"emergency.cloakroom",
		"regionschef.paycheck",
		"emergency.menu",
		"delivery.medic",
		"mission.emergency.transfer",
		"emergency.key",
		"ems.duty",
	},
	["Politi"] = {
		"police.menu",
		"politi.ledelse.doors",
		"police.putinveh",
		"politi.onduty",
		"police.carsearch",
		"player.deletevehicle",
		"police.bodyarmor",
		"bank.police",
		"police.announce",
		"police.check",
		"police.easy_cuff",
		"police.easy_jail",
		"pd.key",
		"police.easy_unjail",
		"police.getoutveh",
		"police.jail",
		"-police.seizable", -- negative permission, police can't seize itself, even if another group add the permission
		"police.seize.items",
		"police.seize.weapons",
		"police.fine",
		"police.service",
		"police.store_weapons",
		"police.store_money",
		"police.wanted",
		"police.besked",
		"police.drag",
		"police.easy_fine",
		"police.garage",
		"policeheli.garage",
		"police.loadshop",
		"police.menu_interaction",
		"police.spikes",
		"police.handcuff",
		"police.license",
		"politiledelse.paycheck",
		"police.cloakroom",
		"police.pc",
		"politi.duty",
		"police.weapons",
	},
	["Mekaniker"] = {
		"mekaniker.paycheck",
		"mekaniker.duty",
		"vehicle.repair",
		"mekaniker.adgang",
		"player.deletevehicle",
		"vehicle.replace",
		"repair.service",
		"repair.loadshop",
		"repair.besked",
		"repair.menu",
		"police.menu_interaction",
	},
	["Mekaniker Chef"] = {
		"mekanikerchef.paycheck",
		"mekaniker.duty",
		"vehicle.repair",
		"mekaniker.adgang",
		"player.deletevehicle",
		"vehicle.replace",
		"repair.service",
		"repair.loadshop",
		"repair.besked",
		"repair.menu",
		"police.menu_interaction",
	},
	["Taxi Chauffør"] = {
		"taxi.service",
		"taxi.garage",
		"taxi.paycheck",
		"taxi.besked",
		"mission.taxi.passenger",
	},
	["Burgershot Medarbejder"] = {
		"burger.service",
		"burger.garage",
		"burger.paycheck",
		"mission.burger",
	},
	["Våbenhandler"] = {
		"blacklisted.weapons",
		"weapons.dealer",
		"player.store_money",
		"våben.garage",
		"weapondealer.paycheck",
	},
	["Kriminel"] = {
		"kriminel.adgang",
		"nojob.paycheck",
	},
	["Advokat"] = {
		"advokat.paycheck",
		"retsag.key",
		"advokat.duty",
		"advokat.service",
	},
	["Miner"] = {
		"miner.adgang",
		"miner.paycheck",
	},

	["Skovhugger"] = {
		"skovhugger.tree",
		"miner.paycheck",
		"skovhugger.adgang",
	},
	["Skraldemand"] = {
		"skralde.vehicle",
		"mission.skraldemand",
	},
	["Pizzabud"] = {
		"delivery.vehicle",
		"delivery.paycheck",
		"delivery.pizza",
	},
	["Farmer"] = {
		"farmer.farm",
		"mission.farmer1",
		"mission.farmer2",
	},
	["Lastbilchauffør"] = {
		"delivery.trucker",
		"trucker.vehicle",
		"trucker.paycheck",
	},
	["Hells Angels"] = {
		"hell.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Members Only"] = {
		"only.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Cartel"] = {
		"cartel.doors",
		"nojob.paycheck",
		"kriminel.adgang",
		"cartel.market",
	},
	["Lost Medlem"] = {
		"lost.doors",
		"nojob.paycheck",
		"kriminel.adgang",
		"lost.market",
	},

	["Lost Ledelse"] = {
		"lost.doors",
		"nojob.paycheck",
		"kriminel.adgang",
		"lost.ledelse",
		"lost.market",
	},

	["Ballas"] = {
		"ballas.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["VatozLocos"] = {
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Mafia"] = {
		"mafia.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["MS-13"] = {
		"ms13.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Royal Reapers"] = {
		"rr.doors",
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Bandidos"] = {
		"nojob.paycheck",
		"kriminel.adgang",
	},
	["Black Army"] = {
		"ba.paycheck",
		"kriminel.adgang",
	},
	["Auto Genbrug"] = {
		"auto.paycheck",
	},
	["Bilforhandler"] = {
		"nojob.paycheck",
		"kriminel.adgang",
		"stripklubben.doors",
	},
	["DVS"] = {
		"dvs.cloakroom",
		"dvs.garage",
		"dvs.shop",
		"dvs.loadshop",
		"police.weapons",
		"dvs.paycheck",
		"dvs.doors",
		"ems.doors",
	},
	["Arbejdsløs"] = {
		"nojob.paycheck",
	},
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
	[1] = { -- give superadmin and admin group to the first created user on the database
		"ledelse",
		"staff",
	},
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
	["Jobcenter"] = {
		_config = { x = 478.90264892578, y = -107.40859985352, z = 63.157897949219, blipid = 181, blipcolor = 4 },
		"Taxi Chauffør",
		"Farmer",
		"Pizzabud",
		"Skraldemand",
		"Lastbilchauffør",
		"Burgershot Medarbejder",
		"Skovhugger",
		"Miner",
		"Kriminel",
		"Arbejdsløs",
	},
	["Politistation Los Santos"] = {
		_config = {
			x = 454.47848510742,
			y = -988.86291503906,
			z = 30.689605712891,
			blipid = 0,
			blipcolor = 0,
			permissions = { "cop.whitelisted" },
		},
		"Rigspolitichef",
		"Vicerigspolitichef",
		"Politidirektør",
		"Chefpolitiinspektør",
		"Politiinspektør",
		"VicePolitiinspektør",
		"PolitiKommissær",
		"Indsatsleder",
		"Politiassistent af 1. grad",
		"Politiassistent",
		"Politibetjent",
		"Politielev",
		"Arbejdsløs",
	},
	["Politistation Paleto Bay"] = {
		_config = {
			x = -436.83581542969,
			y = 6010.0556640625,
			z = 31.616243743896,
			blipid = 0,
			blipcolor = 0,
			permissions = { "cop.whitelisted" },
		},
		"Rigspolitichef",
		"Vicerigspolitichef",
		"Politidirektør",
		"Chefpolitiinspektør",
		"Politiinspektør",
		"VicePolitiinspektør",
		"PolitiKommissær",
		"Indsatsleder",
		"Politiassistent af 1. grad",
		"Politiassistent",
		"Politibetjent",
		"Politielev",
		"Arbejdsløs",
	},
	["Politistation Sandy Shores"] = {
		_config = {
			x = 1850.4310302734,
			y = 3685.8908691406,
			z = 34.286609649658,
			blipid = 0,
			blipcolor = 0,
			permissions = { "cop.whitelisted" },
		},
		"Rigspolitichef",
		"Vicerigspolitichef",
		"Politidirektør",
		"Chefpolitiinspektør",
		"Politiinspektør",
		"VicePolitiinspektør",
		"PolitiKommissær",
		"Indsatsleder",
		"Politiassistent af 1. grad",
		"Politiassistent",
		"Politibetjent",
		"Politielev",
		"Arbejdsløs",
	},
	["Hospital Los Santos"] = {
		_config = {
			x = 312.9475402832,
			y = -594.51129150391,
			z = 43.283985137939,
			blipid = 0,
			blipcolor = 0,
			permissions = { "ems.whitelisted" },
		},
		"Regionschef",
		"Viceregionschef",
		"Stationsleder",
		"Overlæge",
		"Paramedeciner",
		"Akutlæge",
		"Ambulanceredder",
		"AmbulanceElev",
		"Arbejdsløs",
	},
	["Hospital Paleto Bay"] = {
		_config = {
			x = -262.66879272461,
			y = 6311.8735351563,
			z = 32.436370849609,
			blipid = 0,
			blipcolor = 0,
			permissions = { "ems.whitelisted" },
		},
		"Regionschef",
		"Viceregionschef",
		"Stationsleder",
		"Overlæge",
		"Paramedeciner",
		"Akutlæge",
		"Ambulanceredder",
		"AmbulanceElev",
		"Arbejdsløs",
	},
}

return cfg
